#!/usr/bin/python
# This is -*- Python -*-

import pygtk
pygtk.require("2.0")
import gtk

import sys, string, time

sys.path.append("..") # add path for gnoetics library
import gnoetics

import appwindow

#############################################################################

###
### Initial Set-up
###

tri = gnoetics.Trimodel()

sys.stderr.write("*** Loading... ")
t1 = time.time()
count = 0
for txt in gnoetics.Library(dir="../texts-ts"):
    tri.add_text(txt)
    count += 1
    if count > 995:
        break
t2 = time.time()
sys.stderr.write("done. (%.1fs)\n" % (t2-t1))

sys.stderr.write("*** Preparing model... ")
t1 = time.time()
tri.prepare()
t2 = time.time()
sys.stderr.write("done. (%.1fs)\n" % (t2-t1))

sys.stderr.write("\n")

#############################################################################

def die_die_die(b, p):

    i = 0
    p.freeze_changed()
    while i < len(p):
        u = p[i]
        if u.get_flag() and u.is_bound():
            u.set_flag(False)
            if u.is_punctuation() and i+1 < len(p):
                u2 = p[i+1]
                if u2.is_break():
                    poem.unbind(i+1)
            poem.unbind(i)
        else:
            i += 1
    p.thaw_changed()
            
############################################################################

poem = gnoetics.BlankVerse(3, 4)
appwin = appwindow.AppWindow(model=tri)
appwin.set_poem(poem)
appwin.show_all()

gtk.main()
